name: Update HTML File

on:
  workflow_dispatch: # 수동으로 워크플로우를 실행할 수 있게 함
  push:
    branches:
      - main
    paths:
      - "week/01.mon.html"

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update 01.mon.html
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }} # GitHub Secrets에서 토큰 가져오기
        run: |
          echo "파일 수정 중..."
          # 파일 내용을 특정 내용으로 덮어쓰기
          echo "<html><body><h1>업데이트된 내용</h1></body></html>" > week/01.mon.html
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add week/01.mon.html
          git commit -m "자동 업데이트: 01.mon.html"
          git push
